services:
  - type: web
    name: dailyplan-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: JWT_SECRET
        value: your_jwt_secret 